### ISSUE TITLE
Problems in between Vanilla Food Pantry and Upsizer

### ISSUE THREAD

**Issue by ghost** [Wabbit0101/mods_hoardercraft#10]
I have a little problem to install both Mods together.
VFP+Superblocks works properly Superblocks + Upsizer too, Superblocks + VFP also.
Just the combination from VFP + Upsizer is problematic.
I do not allways understand readings(config files) properly.
Could you help me.

I installed just those mods together for testing an found the following  line in the log-File:
java.lang.IllegalArgumentException: Inputs must have a max size of 1 just like water bottles. Brewing Stands override the input with the output when the brewing is done, items that stack would end up getting lost.
the Complete Log is on http://paste.ee/p/0GjLh

**Comment by Wabbit0101** [comment]
Hello jokish363. Yes, this is a problem with up-sizing of potion bottles. I have turned off up-sizing of
up-sizing of potion bottles completely in latest Up-sizer because it causes a lot of issues with brewing recipes (like you see with VFP trying to register a recipe....that's why it's not an issue with other Wabbity mods as they don't do brewing...but it will be a problem for any other third-party mod that is adding new brewing recipes).

**To Fix:**
0) Make sure you grab the latest version of Up-sizer (this will not change water bottles anymore).
1) Move your old up-sizer config file and restart MC so you get a new up-sizer config that does NOT include potion bottles. This should work.

I'll close issue if you can confirm that works OK for you.

**Comment by Wabbit0101** [comment]
Fixed in 1.0-r10 upsizer.
