### ISSUE TITLE
Cannot start Minecraft with SmartHoppers

### ISSUE THREAD

**Issue by varappdev** [Wabbit0101/mods_hoardercraft#100]
I know that is a very old mod and maybe you will never update it again. But please, that mod is a wonderful idea, please fix this. So my Minecraft couldn't start and VanillaFix told me it was because of this mod. Here is the crash report link: https://paste.dimdev.org/ekihuqiziy.mccrash

**Comment by Wabbit0101** [comment]
The issue is most likely with Quark's replacement of vanilla Slime blocks. [Here is a fix that worked for me and others](https://github.com/Wabbit0101/mods_hoardercraft/issues/69#issuecomment-496300860). In a nutshell you need to set in quark's config: `B:"Slime blocks bounce off sides"=false`. If this works for you, you can close out the issue yourself.

As for the future of the mod, it will be rewritten for Minecraft 1.15/1.16 for sure (1.14 is not happening, no point really). It may take some time but I rely on this mod in our family modpack so yea, it will be back...

**Comment by varappdev** [comment]
Thank you, the solution worked. I really do not know how the slime blocks bounciness interfered with smart hoppers, but it worked ¯\_(ツ)_/¯ . Hope to see this mod updated very soon, thanks.

**Comment by varappdev** [comment]
Btw I did not realise this was issue no. 100.

**Comment by Wabbit0101** [comment]
Yup. The incompatibility is that Quark removes vanilla slime blocks (it substitutes its own slime block for the side-bouncy behavior). Some smart hoppers like the packer/unpacker have internal recipe registries. When one of these recipes included a regular _vanilla slime block_ reference, the game would return null or the empty stack -- the mod has a validation step to fail in such a case as the recipe would effectively become a dup exploit point (no inputs = some output). The failing is with 1.12 smart hoppers as it should be able to handle such substitutions.
