### ISSUE TITLE
Instant crash when opening creative tab (VanillaFoodPantry [FORGE])

### ISSUE THREAD

**Issue by varappdev** [Wabbit0101/mods_hoardercraft#112]
My game instantly crashes when I open the creative tab of VanillaFoodPantry. The logs say it's due to some rendering error. Anyways, here is the crash report. 
[crash-2020-06-10_19.28.11-client.txt](https://github.com/Wabbit0101/mods_hoardercraft/files/4760509/crash-2020-06-10_19.28.11-client.txt)

**Comment by varappdev** [comment]
Here is a better crash report: 
[crash-2020-06-10_19.36.54-client.txt](https://github.com/Wabbit0101/mods_hoardercraft/files/4760538/crash-2020-06-10_19.36.54-client.txt)

**Comment by Wabbit0101** [comment]
This crash is probably caused by another mod like food funk; a mod that a) alters other modded items in ways that can be incompatible and b) has a custom renderer. **VFP does nothing with custom rendering or custom item models** which is where you're having issues.

From your crash logs:
```
java.lang.NullPointerException: Rendering item
	at com.wumple.util.config.NameKeys.addNameKeysResLoc(NameKeys.java:123) ~[?:3.6.0] {re:classloading}
	at com.wumple.util.config.NameKeys.getNameKeys(NameKeys.java:51) ~[?:3.6.0] {re:classloading}
```
Here another mod is trying to alter a VFP item on creation and apparently it has a bug that causes a NPE on rendering. You should forward your crash logs to this mod's authors. Perhaps there is some condition or failure the attached capability is not accounting for (my guess I cannot say for sure of course). The items being rendered have layers and properties attached which may be causing issues for this mod's custom code.

Re-open if the mod author says otherwise.

**Comment by Wabbit0101** [comment]
Another thing to try: if that mod has a blacklist config of some kind, try adding VFP items to it (vanillafoodpantry:*) and see if that helps. Or just temporarily disable that mod and see if the problem persists (reopen issue).

**Comment by varappdev** [comment]
The issue is now solved. But can you make it compatible with food funk please? Or do I need to report it to that mod's author?

**Comment by Wabbit0101** [comment]
It is a food funk issue. As noted, that mod's capabilities or rendering is crashing when standard items model attributes are used which means it could crash with any mod using those attributes not just VFP. I cannot fix that. They need to track down and identify the issue their code is having.
