### ISSUE TITLE
Armor Underwear add-on for Survive

### ISSUE THREAD

**Issue by Stereowalker** [Wabbit0101/mods_hoardercraft#119]
Well, I've created the feature request on GitHub

**Comment by Stereowalker** [comment]
So, when you say an API, what really do you require access to? Changing temperatures?

**Comment by Wabbit0101** [comment]
@Stereowalker 
Hello I have been doing some preliminary integration. Give me until end of today (Sun 02 2021) and I will post a small list of thing that would be helpful (I will update this comment). So far the temperature adjustment is proving the most tricky because it's not clear how you're scaling between temperature ranges from just looking at SurviveEvents and even if I stand right next to a source block of lava (in a plains biome) without any armor -- there isn't any change to my player temperature! (Normal game level, survival mode). Currently using 3.0.5 version...

**Comment by Wabbit0101** [comment]
The promised list (a little late sorry, but I wanted to make sure I had good idea how Survive's internals work)

I have got a good handle on how I might integrate with Survive for several of my mods: Armor Underwear (temperature) and VanillaFoodPantry (hunger/thirst/stamina), PinklySheep (everything). Alas I was not able to finish for a few reasons: here are my thoughts/reasons. (LONG. Please PM for specifics, or better, leave any questions in follow-up comments.) 

**Kudos**
Nice mod! It *is* neat that core body temp is the underlying mechanism being emulated...that's pretty cool IMO. As I was integrating multiple mods, I kept thinking "ooo.... this is gonna be good when finished!" I am really looking forward to completing the integration.

**Advice offered (enhancements..emphasis temperature mechanics)**
- Formalize the ORDERING of computation for wetness, temperature (right now it's indeterminate)
- [BIG ONE] Provide a hook into the main player temperature computation chain (and do it after your base environment considerations have been done). Without this I cannot port the bulk of Armor Underwear to Survive. Lots of ways to do a hook: IMC, capabilities, custom events, etc.
- [BIG ONE] In your LivingUpdateEvent hooks, check the applicability (tick modulo) BEFORE doing all the temperature calculations (unless there are side-effects...but I did not notice any while trying to debug my stuff).
- Armor temperature support should not rely on material solely. Without a hook (previous point) this is very limiting.
- Add baubles/curios support. You could also tweak your armor iteration to use itemstack handlers instead of assuming simple vanilla layout. I was thinking this might be a way to support portable goo paks but seems to be a good idea in general.
- Block/TileEntity support. Like for armor, block support should also consider BlockState not just the shared Block for the temperature mapping. (Yea...not sure how you would do this either without supporting capabilities)
- For thirst/hydration support you might try supporting datapack tag groups in addition to config. This allows mod-authors/modpacks to do most of the mapping heavy lifting for you while letting players tweak their stuff. (Example you define anything in "drinks/juice" to give 5pts of thirst, and .1 hydration...as a mod author if I've got an item that is like juice I just define this tag...and viola! Survive integration). You could also make your config support tags (put a '#' in front of the items name to indicate values for a tag).
- Seems it would be possible to rely mostly on LivingEntity...but some temperature computations require PlayerEntity for some reason. Unless required, APIs should use LivingEntity (this would, I think, allow Survive support for NPEs like horses, dogs, and other companions...an intriguing extension).

**Issues encountered**
- Using core body temperature as the player-facing temperature is awkward as it's really not a perspective most people in reality (other than physicians) use.  The graphical HUD bars helps here but you say there are some issues with that view.
- The Fahrenheit numbers HUD seems broken (the conversion)
- Player HUD flickers a lot when Survive present (but this might just be my potato graphics)

**Comment by Stereowalker** [comment]
You seem to be using an outdated version of the mod, because you stated that the temperatures are reliant on armor materials. There have been two major changes since then.
1, armor temperatures are no longer dependent on armor materials as there are armors available that don't rely on this function

2, body temperatures are now manipulated by temperature modifiers. This allows other mods to manipulate the temperature more freely, and it allows for everyone to see exactly what is manipulating the body's temperature. Though adding an event here will also allow for more dynamic manipulation.

As for your remaining suggestions, I'll take them into serious consideration for the next release

**Comment by Wabbit0101** [comment]
Uploaded initial stab at Survive support in Armor Underwear on CurseForge: [https://www.curseforge.com/minecraft/mc-mods/armor-underwear-mod/files/3172173](https://www.curseforge.com/minecraft/mc-mods/armor-underwear-mod/files/3172173). Post new issues as needed.
