### ISSUE TITLE
VFP - some recipes works different

### ISSUE THREAD

**Issue by Dushess** [Wabbit0101/mods_hoardercraft#123]
Or completely different (=doesn't work)
modlist is here, gonna place issue here...
![1 16 4 modpack](https://user-images.githubusercontent.com/15954961/105616203-51baf400-5de6-11eb-9539-f6d55cc965a9.png)

version vanillafoodpantry-mc1.16.4-6.0b2.jar

**Detailed description:**
butcher's meat cutter can't be crafted at all,
flint cutter uses horizontal placement,
wheat can be transformed directly to flour without any agents (not a bug tbh, like different options for various instances of wheats),
leavening agent doesn't appearing with _any seeds_.

Just what I've found.

**Comment by Dushess** [comment]
Need to check a recipe conflicts, any known info from this list? (1st is renamed, this is exactly barrels .Also there's no same things to be a conflict... hmm)
Also wheat recipe got fixed by super_compatibility_mode = true

**Comment by Wabbit0101** [comment]
Best I can advise is to install a recipe conflict handler mod like Polymorph. Also attach your config files (wabbity_carrots.toml and wabbity_vanillafoodpantry.toml). What version of Minecraft/Forge are you using?
- Check your logs for any issues loading recipes or data tags (this will block recipes often)
- Butchering axe recipe works for me SP and DS. No idea what would conflict with this recipe.
- Flint Cutter's recipe is a horizontal shaped recipe; this prevent conflicts with a zillion modpacks that include flint shears
- There are two recipes for flour (a simple one that you're referring to) and a VFP one. The simple one many modpacks remove due to conflicts. You can remove it for your own game by turning on supercompatibility mode in the configs.
- Leavening Agent not appearing (I'm not sure what this means), but if you don't see the recipe even for VFP's own Dried Seeds then another mod is interfering or if you're using a custom crafting table (or replaced core mod) that could be your issue...I'm just guessing

You're using MultiMC so you can quickly create an instance with just VFP. Check if your issues exist in this instance; if not it's probably just some conflicts you'll need to find and resolve.

**Comment by Wabbit0101** [comment]
PS: Apologies if you're reading the CurseForge hosted docs which are for the 1.12 version of the mod (some recipe pics would be out-of-date). Since CurseForge was bought out (twice now!), the site editor is atrocious and updating anything would destroy what's there so it's been left as-is. No time to create new docs on wiki yet.

**Comment by Dushess** [comment]
That's why, got it. Maybe a picture of it or where to look inside of jar?

**Comment by Dushess** [comment]
Leavening agent - wrong sugar, but visually vanilla sugar is absolutelu same.
