### ISSUE TITLE
Armor Underwear ozzie liner recipes not enabled unless include_special_items = true

### ISSUE THREAD

**Issue by Lyle-Tafoya** [Wabbit0101/mods_hoardercraft#133]
The comment in the config file above the special_liners_craftable option says "Set to "true" to include crafting recipes for some liners (and materials) that are normally obtained through other mechanisms like looting or advancements. By default, only the temperature-related 'Ozzy' liners are craftable."

So according to that, ozzy liners should be craftable by default. However, the recipes appear to be disabled. I tried changing special_liners_craftable to true and I still could not craft ozzy liners. However, when I set include_special_items = true the ozzy liner recipes get enabled. However, it also enables liners that I don't want. I would prefer for the ozzy liner recipes to be enabled without this option, as indicated by the above-cited comment. The comment above the include_speical_items option says "Set to true to enable special items unrelated to temperature management". Since ozzie liners ARE related to temperature management, they shouldn't be gated behind this option, right? I would fix it myself, but I don't see the source?

**Comment by Wabbit0101** [comment]
In hindsight, perhaps the configuration names could be better and the comment clearer, but the mod is behaving as it should. By default all the core temperature-related liners are defined: the simple ones and the auto-regulating ozzy one. But because ozzy liners are technically special liners (ie OP) _their crafting_ is disabled unless special liners are explicitly enabled. Modpacks can simply include a recipe for ozzy liners themselves w/o activating all the other specialty liners if they want an easy craft for the autoreg liners too.

**Comment by Lyle-Tafoya** [comment]
Okay, I understand now. I added the recipes in a datapack and got it working the way I want. Thank you.
