### ISSUE TITLE
SuperBlocks BIG Buckets replenish all their content on one go.

### ISSUE THREAD

**Issue by AfterRebelion** [Wabbit0101/mods_hoardercraft#14]
Minecraft 1.11
When you have an empty BIG bucket, and you right click on a liquid, it will replenish all uses of the bucket, instead of adding one. This can make it to a an "early" infinite lava generator, with only 48 iron ingots.

**Comment by Wabbit0101** [comment]
This is by design. A big bucket is 16 buckets of stuff rolled into one with convenience of single pickup. If a player is smart enough to figure out the "use last bucket to 'refill' self trick" that's also fine (and very useful). Recall this is modded minecraft...trying to pretend it's the same as early game vanilla isn't really going to work.
