### ISSUE TITLE
[Carrots lib + AUw] 1.19.2 Support

### ISSUE THREAD

**Issue by ColonelGerdauf** [Wabbit0101/mods_hoardercraft#159]
It will be nice to support this sub-version, for the sake of modpack compatibility. 1.19.4 is indeed the latest, but due to breaking updates and how they were rolled out, it lacks the mod support that 1.19.2 enjoys.

**Comment by Wabbit0101** [comment]
Unfortunately I have time to manage one porting effort only. 

As you alluded to, 1.19.2  is significantly different from 1.18.2 which is significantly different from 1.19.4, which is different (though less so) from 1.20.x. A 1.19.2 port would be a lot of work and would basically have had to be redone again on the way to 1.20.1. The 1.19.4 version was selected because it would require the least rewriting for _all related mods_ to get to 1.20.x versions.

I know 1.19.4 isn't very used for pack-makers, but as AUw isn't much used since 1.12.2/1.16.5, I believe the limited coding time is better put pushing to 1.20.1 and all those lovely armor trims and sherds :)

**Comment by ColonelGerdauf** [comment]
With all due respect, there has been little tangible progress since the first 1.19.4 beta. I have seen nothing as far as a 1.20.x mod goes, and Cold Sweat has introduced explicit AUw compat, so having the mod absent in 1.19.2 up to now is quite awkward.

Alongside explicit support, there is a growing input in the comments for 1.19.2 support, so I wouldn't dismiss post-1.16.5 as "not used much".

**Comment by ColonelGerdauf** [comment]
Now that 1.20.1 is picking up steam, with Tinkers Construct in particular, the situation about the lack of popularity with 1.19.4 is starkly apparent.
