### ISSUE TITLE
[1.11.2/3.1] GlowGlass not working?

### ISSUE THREAD

**Issue by Malkierian** [Wabbit0101/mods_hoardercraft#17]
Now, granted, there is very little documentation on how exactly to get the glowglass working (finding where to get luminescence was difficult enough).  But, when I crafted clear and white glowglass, neither the Thick variety nor the Very Bright variety of either actually emitted any light.  I tried one block and an array of up to 3x3, and it didn't do anything.

**Comment by Wabbit0101** [comment]
The wiki pages are on CurseForge -- they should've helped you with documentation and there is a section for luminesce. Are you crafting Glow-Glass or Powered Glow-Glass? Please include the recipe you're using.

**Comment by Malkierian** [comment]
Huh.  The wiki page didn't say anything about needing redstone to turn on the glow glass.  The name kind of implied that wouldn't be necessary.  But it does say that there is "always on" glow glass, and doesn't say anything about the recipe for it.  I'm using the recipe with thick glass and two redstone dusts.

**Comment by Wabbit0101** [comment]
Yea...I stopped using CurseForge wiki (called pages)...nobody seems to read them!...In case you're interested, read here: https://minecraft.curseforge.com/projects/superblocks-mod/pages/strong-glass-blocks. 
I think you're making the powered glass as you mention redstone...Try using just thick glass + luminesce...then put down that block in a dark place. It should work fine. The page also contains examples for colored glow glass. Post any more issues here.

**Comment by Malkierian** [comment]
No, I've been looking at that the entire time, and had seen it before I even posted the issu, lol.  You just weren't specific enough on that page to say that just glowglass is what glows on its own.  Especially when considering that many other mods require redstone to make any kind of lighting, your powered variety implied, to me at least, that there was some added variant on the redstone recipe to make it glow on its own (usually others add a redstone torch to make it inverted).  I guess, then, this is an issue with the wiki, not with functionality.  Now that I know the functionality, the naming scheme makes sense XD

**Comment by Wabbit0101** [comment]
Um. The wiki says it right there and it gives a recipe picture: "Glowing strong glass does just that -- it glows or acts as a light source in proportion to its thickness."  I'm not sure what else it would say; it say nothing about redstone because redstone is not required. Your interpretion based on your experience with other mods is something I cannot predict: From the POWERED glow glass section: "The... powered lamps, like their "always on" glow glass cousins, give off the amount of light that matches".... The powered section explicitly says that the regular glow glass is always on and it compares the powered glass to redstone lamps which must be POWERED. Hence 'Glow Glass' vs 'Powered Glow Glass'...
