### ISSUE TITLE
VanillaFoodPantry requires its own salt rather than accepting dustSalt

### ISSUE THREAD

**Issue by darloth** [Wabbit0101/mods_hoardercraft#19]
Many mods have salt of some kind or another.

VanillaFoodPantry's salt is defined as dustSalt in the ore dictionary, but the foods that require salting cannot be salted with, say, Mekanism dustSalt.

Is that intentional?

**Comment by Wabbit0101** [comment]
Without knowing the specific recipe(s) you're referring to I cannot say for sure. However, VFP uses a 'portionSalt' and 'portionSaltSmall' not dustSalt in its recipes. The dustSalt definition is for other mods to use VFP's salt if the player chooses.

**Comment by darloth** [comment]
Fair enough, and if you decide not to change anything I understand that it works well as it is currently - but from an end user perspective it looks odd.

There's a pile of salt, it works.  There's a similar pile of salt, it doesn't.

Is there a reason that the receipes can't accept dustSalt instead of specifically portionSalt? (presumably, including the one to make portionSaltSmalls out of portionSalts)

At present I can't remember the exact recipe either, but I'm reasonably sure it was one that used a whole ground salt item, so not one of the small ones.

**Comment by Wabbit0101** [comment]
Yea...this is an ongoing no-good-way-to-fix thing. Basically VFP is a bit 'picky' with regard to generic ids like 'dustSalt' because it can refer to salt that isn't edible. Like 'egg' can refer to a pigeon egg or a dinosaur egg...so having both create a simple fried egg is always fun to explain. It's not a very big mod so people usually ask to go the other way (use VFP items in other mod recipes hence 'dustSalt'). Let me know the name of your mod that creates salt. I'll see if it's ez to put a mapping in VFP.

**Comment by Wabbit0101** [comment]
Addressed in 3.2 release.
