### ISSUE TITLE
Crash SmartHoppers with Better With Mods

### ISSUE THREAD

**Issue by pupnewfster** [Wabbit0101/mods_hoardercraft#30]
Crash Report: https://pastebin.com/9kByzVd8
Smart Hoppers Version: mc1.12-4.0
Better With Mods Version: 1.12-2.0.28
Forge Version: 1.12.2-14.23.2.2625

The_Wabbit response on curseforge:
> BetterWithMods may be altering enderchests or obsidian blocks for some reason. The following is failing an assertion that checks an ItemStack created with these items is non-empty.
> 
> addRecycleRecipe(new ItemStack(Blocks.ENDER_CHEST), new ItemStack(Blocks.OBSIDIAN,6));
> As a temporary measure you can try disabling recycling and autocrafting altogether as it's likely to have issues with other items BetterWithMods is changing besides these two. Please open an issue at https://github.com/Wabbit0101/mods_hoardercraft/issues so I can check properly.

Disabling recycling and autocrafting as suggested does prevent it from crashing.

**Comment by Wabbit0101** [comment]
From the log files. BetterWithMods is replacing the standard ender chest and beacons.
>> [20:11:19] [main/INFO] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `ender_chest`, expected `betterwithmods`. This could be a intended override, but in most cases indicates a broken mod.

**Comment by DaedalusGame** [comment]
not sure why this happens exactly but I assume you're registering those recipes in preInit which is too early. You can move the recipe registration to init or the recipe registry event to hopefully restore compatibility

**Comment by Wabbit0101** [comment]
The installation code is running after the mod's Item/Block registry events so it assumes it's safe to access _vanilla_ ItemStacks at this point. It's not based off the recipe registry events because this code is not registering any recipes (yea I know it seez 'recipe' but its used generically). I investigated a little and it seems Itemstacks created with blocks like the vanilla enderchest or beacon return isEmpty as TRUE (which triggers some state/args assertions). 

Anyhoos, these particular features of SmartHoppers don't make much sense with betterwithmods installed so I have added some integration that disables a subset of features when certain base assumptions aren't true (as would be for betterwithmods, primal, etc....which have gating for certain resources)

**Comment by Wabbit0101** [comment]
Fixed in 4.1 release; see previous comment.

**Comment by DaedalusGame** [comment]
I know that it's odd, but the only time it's safe to access *any* item or block is after all item registry events have finished. (This actually technically applies to your own items and blocks aswell, since mods can alias *anything* that is a registry impl now, but this usually creates a complete logistical nightmare) Kudos for the integration though.
