### ISSUE TITLE
Add unbaked pumpkin pies and cakes

### ISSUE THREAD

**Issue by WrongWeekend** [Wabbit0101/mods_hoardercraft#36]
These two items would have more consistency if they had recipes for unbaked versions using the same types of ingredients as their modded counterparts from VFP.

**Comment by Wabbit0101** [comment]
Am adding an VFP pumpkin pie variant (same food points but better saturation) and a VFP-ish cake recipe (but not a new final item). Instead I've added "cake slices" which gives a player a bit more incentive to make a cake in the first place although the slices will not drop from a broken cake block as they are a few mods that already do this..

**Comment by WrongWeekend** [comment]
I would also suggest adding unbaked cookies (including for the VFP ones which don't seem to require baking) and uncooked mushroom/rabbit/beetroot stews. I think stews in general may also be a good way to combine the bit o' items together.

**Comment by Wabbit0101** [comment]
Thanks for the feedback:

The cookies do not have unbaked versions because frankly they're not worth it (this is a valid argument for cakes as well unless they're used in maps as aid posts for players). In general these sugary items appeal greatly to younger players (for my worlds anyways) and I make it easy for them to make 'em. Example: the Gelos seem to be the most useless food to me, but man they just love them. 

Basic stews, stew replacements, and apple pies are done to death by sooo many other mods that I've not added any of these as VFP is very unlikely to be the only food mod present. My intent is to supplement and extend and not duplicate too much. Making everything require baking is also not the intent of the mod. One of my big tests is whether you can use VFP to create a variety of good food within your player 2x2 crafting grid on-the-go (think Spice of Life or Nutrition or TAN forcing you to eat something beside steak and chicken even if you're up to your eyeballs in dungeon mobs). With that criteria, making some VFP foods at least match but hopefully exceed the utility of the better Minecraft food (like beet and mushroom stew!) on-the-go is a focus. That's the main reason for example, why the creamed soups do not require cooking and accept all max-stackable powdered versions of ingredients.

Not sure what to do with your left over bits o' stuff? Have you tried some overstuffed potatoes or nugget meals...Any ideas (other than mawh stews) welcome!

**Comment by Wabbit0101** [comment]
See release 4.2 at https://minecraft.curseforge.com/projects/vanillafoodpantry-mod/files/2568445.
