### ISSUE TITLE
[1.12.2] Crafting?

### ISSUE THREAD

**Issue by BuilderDan** [Wabbit0101/mods_hoardercraft#44]
Getting this odd glitch:
![image](https://user-images.githubusercontent.com/19805371/40447014-07480474-5e86-11e8-94d0-5c599da630a5.png)

Happens with every item that doesn't have an output recipe for crafting...

Forge: forge-1.12.2-14.23.3.2675-universal.jar
Mod Version: smarthoppers-mc1.12-4.1.1.jar

**Comment by BuilderDan** [comment]
Mods List:

Better Builder's Wands (by Portablejim)
Bloodmoon (by lumien231)
ATLCraft Candles Mod (by AllTheLayers)
Better Advancements (by Way2muchnoise)
AmbientSounds 2.0 (by CreativeMD)
Bullseye (by Glitchfiend)
AutoRegLib (by Vazkii)
Better Underground (by kenijey)
Better Foliage (by octarine_noise)
Baubles (by azanor)
Better With Addons (by BordListian)
Better Placement (by tterrag1098)
Bauble of Undying (by InsomniaKitten)
AppleCore (by squeek502)
BetterFps (by Guichaguri)
Better With Mods (by BeetoGuy)
AppleSkin (by squeek502)
Better Than Mending (by legobmw99)
Armor Sound Tweak (by InsomniaKitten)
VanillaFoodPantry Mod (by The_Wabbit)
Potion Core (by Tmtravlr)
JEI Integration (by SnowShock35)
Simplified Horses (by Fusseel)
Morpheus (by Quetzi)
Mo' Villages (by The_WeatherPony)
CplPibald's Tweaks (by CplPibald)
Pretty Beaches (by BlayTheNinth)
Login Shield (by Glasspelican)
Dynamic Surroundings (by OreCruncher)
Smooth Font (by bre2el)
RandomPatches (by TheRandomLabs)
Leather Works (by cleverpanda714)
Nether Chest (by mangoose3039)
Simulated Nights (by MolecularPhylo)
The Weirding Gadget (by AtomicBlom)
Natural Baby Animals (by Insane96MCP)
Mod Name Tooltip (by mezz)
GravelMiner (by BlayTheNinth)
Waystones (by BlayTheNinth)
Durability Notifier (by mrbysco)
The One Probe (by McJty)
Serene Seasons (by Glitchfiend)
Lapis Stays in the Enchanting Table (by csb987)
Friendly Fire (by Darkhax)
Placebo (by Shadows_of_Fire)
Primitive Mobs (by Daveyx0)
FTBLib (by FTB)
SmoothWater (by asiekierka)
Combustive Fishing (by theillusivec4)
Tumbleweed (by konwboj)
SmartHoppers-Mod (by The_Wabbit)
Hunger Overhaul (by progwml6)
Light Level Overlay Reloaded (by oldjunyi)
Just a Few Fish (by Tmtravlr)
Ore Excavation (by Funwayguy)
SwingThroughGrass (by exidex)
Rustic (by mangoose3039)
ItemZoom (by mezz)
ShetiPhianCore (by ShetiPhian)
Solar Flux Reborn (by apengu_)
Controlling (by jaredlll08)
Muon (by TrinaryLogic)
CookieCore (by EphysPotato)
Comforts (by theillusivec4)
Potion Fingers (by Vazkii)
Hammer Core (by apengu_)
Roost (by timrwood)
VanillaAutomation (by universaI)
Underwater Chest Bubbles (by Squirtle8459)
Painting Selection Gui Revamped (by senpaisubaraki)
RandomTweaks (by TheRandomLabs)
Wither Skeleton Tweaks (by Shadows_of_Fire)
Quality Tools (by Tmtravlr)
Just Enough Resources (JER) (by Way2muchnoise)
Mantle (by mDiyo)
Wolf Armor and Storage (by CenturionFox)
Roots (by elucent)
Smart HUD (by InsomniaKitten)
Magic Feather (by EphysPotato)
FPS Reducer (by bre2el)
JourneyMap (by techbrew)
EasierVillagerTrading (by Thorgeig)
Ore Shrubs (by Lhykos)
LightOrbs | Fireflies and companions (by cobradarkponey)
FTB Utilities (by FTB)
Maille (by cleverpanda714)
Metamorph (by horsewithnoname)
Familiar Fauna (by Glitchfiend)
Village Names (by AstroTibs)
Sound Filters (by Tmtravlr)
Refined Storage (by raoulvdberge)
Placeable Items (by Ferdz)
XP From Harvest (by ReaIGecko)
SecretRoomsMod (by AbrarSyed)
Not Enough Roofs (by blenderfan)
[ANGRY PIXEL] The Betweenlands (by MrCompost)
Roguelike Dungeons (by Greymerk)
Shoulder Surfing Reloaded (by suinhas)
Snad (by TheRoBrit)
Totem Expansion (by lemonszz)
Redstone Flux (by TeamCoFH)
Traverse (by ProfessorProspector)
Inventory Tweaks (by Kobata)
Electroblob's Wizardry (by electroblob)
NetherPortalFix (by BlayTheNinth)
Platforms (by ShetiPhian)
Fast Leaf Decay (by Olafskii)
Just Enough Items (JEI) (by mezz)
Magma Monsters (by Kashdeya)
OpenableWindows (by insaneau)
Persistent Cake (by InsomniaKitten)
Carry On (by Tschipp)
Upsizer Mod (by The_Wabbit)
Spartan Shields (by ObliviousSpartan)
Permafrost (by Virtuoel)
Waddles (by Girafi)
Naturalized (by Jeffyjeff_yt)
Better Vanilla [16x] (by fisher521)
Overlays Pack (by tomaxed44)
The Twilight Forest (by Benimatic)
MegaLoot (by Winter_Grave)
Dye It Yourself (by Poke1650)
Fairy Lights (by pau101)
Diet Hoppers (by RWTema)
stimmedcow : NoMoreRecipeConflict (by Oliv1er)
Redstone Paste (by FyberOptic)

**Comment by BuilderDan** [comment]
I can test it alone and add mods one by one, but I really don't have the time for that right now and honestly if thats the case, then I'll just remove it from my pack for now.

**Comment by Wabbit0101** [comment]
Yes and no...it just delays until the next breakage. Basically mods like betterwithmods is replacing much of core vanilla game with their own interpretation using Forge's replacement mechanism (so it's legal to do so). But now other mods need to assume nothing Mojang installs is valid (like hopper references) and rewrite their code accordingly; i.e don't use Items.xyz or Blocks.xyz. This is a royal pita. As I avoid such mods like the plague, I fix issues as the 5-10 people who actually use this mod reports them :)

This particular bug is caused because the programmatic installation of this recipe (not jsonified yet), uses mojang's hopper reference...which bwm has nerfed via replacement...using that reference results in an empty stack which for some reason the recipe matcher equates to a wild card. 

You can try to disable the recipe: 'smarthoppers:skinny_hopper_from_hopper' see if that helps. It's marked as a SmH bug now; I'll look into patching it soon.

**Comment by BuilderDan** [comment]
Thank you! And ye, I'm not a huge fan of betterwithmods, but I like better with add-ons and it requires BWM.

**Comment by GlobbyPotato** [comment]
Hi, I'm getting the same problem where everything crafts into a Skinny Hopper. 
It looks like the problem may come from Diet Hopper because they change something in the vanilla hoope core code or so. There was a similar issue with the mod Uppers which changed vanilla hopper into their hopper causing the same problem. Any confirm of this for this case?

**Comment by Wabbit0101** [comment]
The next version will have those recipes removed except in development. After some checking, I have no idea which mod is stomping on what for whichever reason...Those recipes were added as conveniences to let players reuse their current hoppers. As they're not essential to the mod, I'll just nerf them. 

If you're still having issues in your modpack after the next version, as I've recommended above, you should just remove SmartHoppers because it really expects vanilla hoppers.

**Comment by Wabbit0101** [comment]
It may be the diet-hoppers mod. I've uploaded a 4.1.2 version w/ these recipes removed. See if it fixes your issue. https://minecraft.curseforge.com/projects/smarthoppers-mod/files/2573533
