### ISSUE TITLE
Skinny Hopper Recipe

### ISSUE THREAD

**Issue by joshingjosha** [Wabbit0101/mods_hoardercraft#48]
The skinny hopper has an extra recipe which is blank. Any item placed in a crafting table (which on it's own doesn't form a recipe) produces a skinny hopper. For example, an oak log will form planks but a plank (which on it's own doesn't make anything) forms a skinny hopper.

**Comment by Wabbit0101** [comment]
See issue #44 . I believe the root cause is a another mod that replaces or removes the vanilla hopper items. I have a patch to remove these one-to-one hopper-based recipes from smarthoppers as they are just conveniences and aren't necessary. Look for the patch in a day or two (have to regress test it).

**Comment by joshingjosha** [comment]
Thanks! I didn't realise that there would be such a quick response! :)

**Comment by Wabbit0101** [comment]
I've uploaded a 4.1.2 version w/ these recipes removed. See if it fixes your issue. https://minecraft.curseforge.com/projects/smarthoppers-mod/files/2573533
