### ISSUE TITLE
[VanillaFoodPantry][Suggestion] Option to disable cartons and bags

### ISSUE THREAD

**Issue by Mike-U5** [Wabbit0101/mods_hoardercraft#53]
Cartons and Bags of food are not really needed if you have any kind of storage mod installed.
They do however, really clog up JEI recipes and item lists.
A config option to disable them (prevent them from loading entirely) could really help there. :)

**Comment by Wabbit0101** [comment]
They aren't meant as a mass tech storage system; they're to aid with standard chest and player inventory storage which is what most folks using this mod have. Please explain how they're _clogging up_ your JEI recipes and item lists? If you're playing a mod pack, then ask the pack author to disable those recipes because, as you point it, VFP should properly not be there (it's also possible to remove the recipes yourself).
