### ISSUE TITLE
PinklySheep CTD with Dynamic Trees

### ISSUE THREAD

**Issue by TakunSho** [Wabbit0101/mods_hoardercraft#54]
Minecraft: 1.12.2
Forge: 2757
Dynamic Trees: 0.7.8
PinklySheep: 4.0b6

When I break a vanilla (oak) dynamic tree, I CTD due to a PinklySheep drop by the sounds of the error that generates.

[crash-2018-08-19_18.40.31-client.txt](https://github.com/Wabbit0101/mods_hoardercraft/files/2300760/crash-2018-08-19_18.40.31-client.txt)
[2018-08-19-2.log](https://github.com/Wabbit0101/mods_hoardercraft/files/2300761/2018-08-19-2.log)

**Comment by Wabbit0101** [comment]
Hmm, this says your active hand is undefined which is impossible. When you say "I break a vanilla (oak) dynamic tree" what does that mean? Are you using an axe or your hand or some other method. Thanks.

Also if possible, can you check if the crash occurs in the recommended Forge build 2705. 2757 is a latest unstable build (the crash report line# do not match up). From the stack Player.getActiveHand is NULL which it should never unless there is a lib-mismatch.

**Comment by TakunSho** [comment]
That's interesting, I was breaking it with my empty hand I think, though it might have been a stone axe. I'll test both shortly. I seem to recall I have a few mods that the mod authors decided newer versions of forge were required, I'll have to double check. I'll try turning those off an rolling back to 2705.

**Comment by TakunSho** [comment]
Minecraft: 1.12.2
Forge: 2705
Dynamic Trees: 0.7.8
PinklySheep: 4.0b6
BetterWithMods: 2.3.9 (just in case this is part of the issue)

Alright, the only mods that were beyond 2705 were CodeChickenLib and Ender Storage, so I just rolled them back in addition to rolling back forge to 2705. So I accidentally left clicked it with bonemeal in my hand and it crashed for the same reason (in creative). And this happened in single-player, not on the server. Whereas previously I was connected to the server and in survival. It only happens when the tree breaks. 

As a side note, the drops that should be there (sawdust, bark, planks, acorns: Better with Mods and Dynamic Trees) all drop and are on the ground or in my inventory when I relaunch. If any Pinklysheep items are supposed to drop, like resin or something, I'm not getting those.

For clarification, I meant it was a dynamic tree, but it was an oak tree not a mod added tree (so another mod should not be interacting with it except for any drops an oak tree would give).

I also tested with a stone axe and it crashed for the same reason as well.

[crash with bonemeal/creative](https://github.com/Wabbit0101/mods_hoardercraft/files/2306432/crash-2018-08-21_09.28.45-client.txt)
[latest.log from bonemeal](https://github.com/Wabbit0101/mods_hoardercraft/files/2306904/2018-08-21-5.log)


[crash with stone axe/survival](https://github.com/Wabbit0101/mods_hoardercraft/files/2306433/crash-2018-08-21_09.17.33-client.txt)
[latest.log from stone axe](https://github.com/Wabbit0101/mods_hoardercraft/files/2306434/latest.log)

**Comment by TakunSho** [comment]
Sorry, I initially gave the wrong log file for the bonemeal, I have fixed it.

**Comment by Wabbit0101** [comment]
I think what's happening is that the event that DynamicTrees is issuing to get drops has not properly setup the support environment for that event...in particular for players, the active hand variable has not been set, so any code doing "Player::getActiveHand" is going to trigger a NPE.

Within DynamicTrees itself, the code (BlockBranch@408) make a single assumption encapsulated as:
`ItemStack heldItem = player.getHeldItemMainhand();`

DynamicTrees assumes the block is being replaced by player action ONLY from the main hand so it does not itself trigger the issue (change that assumption and I'll bet $$ it barfs). Pinklysheep however, does not make this main-hand-only assumption and as part of it's processing uses an alternate API called `Player::getActiveHand` which works for tools that function from the offhand as well. It is this method that seems to be returning NULL and causing the havoc. (Yes, why this would _ever_ be set null is a good question...but it is for whatever reason.) I will fortify the PinklySheep code, but you might reference this with the DT mod author as well.

**Comment by TakunSho** [comment]
I was already recomposing this issue over on their github. And that makes total sense. I will give them this information.

**Comment by ghost** [comment]
I made the changes according to your suggestions.  Let me know.

**Comment by ghost** [comment]
It turns out that I did not make the changes according to your suggestions like I thought I did.  I can't understand what it is that you're asking.  You are correct that I'm assuming that the block in removedByPlayer is being replaced by player action only from the main hand.  Why would I assume otherwise?  I'm willing to get this coded right but I might need a little help because the circumstances seem pretty strange to me.

**Comment by Wabbit0101** [comment]
Lemme just start by saying I don't know if this is fundamentally a DT issue. Why EntityPlayer would have an active hand value of null while a having a selected hotbar slot with an item is a general question. So this may not be your problem to fix...

Having said that, the core issue here is that if any mod triggered by the DT fired harvesting event tries to use `EntityPlayer.getActiveHand`, it will get `null` instead of `MAINHAND` or `OFFHAND`. Null is unexpected here given that it implies the mod's code is being called in response  to an explicit situation that says "hey something has been harvested by an entity that is a real player (event.harvester is non-null and not a fake player) who apparently did it with no hands". For tools that can be used from the offhand, if the handler always assumed the mainhand, it would pick the wrong held item. _Remember the harvest handler is called for any harvesting event_, not just the DT tree-chopping-by-axe event that is specific to this issue.

In response to your question: "I'm assuming that the block in removedByPlayer is being replaced by player action only from the main hand. Why would I assume otherwise?"...I guess the simple answer is because as of 1.9 that might be an invalid assumption. Items can be used from both hands and there are certainly modded tools that can be used from either hand. A contrived example: a slow multipurpose axe that I can use from my offhand with my sharp sword in my mainhand as I hack through a jungle filled with things trying to eat me. Right-clicking at a log triggers the _axe's use_, not the sword's; based on your assumption DT will think my sword chopped down the tree which is wrong.

Back to this issue: I've changed PinklySheep so this issue reported here is taken care off (it assumes the result of getActiveHand is @nullable as of now).

**Comment by Wabbit0101** [comment]
Seems to be ok without any DT changes if Pinklysheep defaults to mainhand if activeHand is marked null. Closing this issue.
