### ISSUE TITLE
Somehow have four extra hearts after death

### ISSUE THREAD

**Issue by darthvader45** [Wabbit0101/mods_hoardercraft#57]
For some odd reason, when I died with at least toughness 1 or 2 (had four extra hearts), I respawned with exactly the same amount of health.  I even kept the four extra hearts.  I've even kept em through several deaths.  It's a bit amusing, and can be almost considered an exploit.  Can this even be patched?

**Comment by Wabbit0101** [comment]
Which mod is this issue related to?

**Comment by darthvader45** [comment]
vanilla food pantry.

**Comment by Wabbit0101** [comment]
I'm not sure how VFP is connected to this. Where are you getting the extra hearts from? VFP doesn't do anything to player's max health or have any hooks into events like login/respawn. Why do you think this is VFP related? Is it a VFP potion? Also please indicate the Forge and VFP versions you're using.

**Comment by darthvader45** [comment]
It was due to the Toughness status effect, usually given when the nutrition level for something like protein gets at or above 90%.  

VFP: 4.2.3
Forge: 14.23.5.2768

**Comment by Wabbit0101** [comment]
So I will assume the Nutrition mod is the one putting the hearts back for the player via its Toughness effect.  This doesn't sound like VFP is causing your issue. You might want to ping the Nutrition mod's author.

There is an outstanding issue with VFP's tonics that,  by default, they are not removed with milk (this is fixed in the upcoming 4.3.1 version for sometime this week). But this doesn't sound related.

**Comment by Wabbit0101** [comment]
Reopen if this is not a Nutrition mod issue (VFP does not install the Toughness effect causing the extra hearts, etc.). See previous comment.
