### ISSUE TITLE
Crash: Unable to create dynamic VFP multi-block vegetable_carton

### ISSUE THREAD

**Issue by Rongmario** [Wabbit0101/mods_hoardercraft#65]
Log: https://paste.ee/p/yOHSa

Crash: https://paste.dimdev.org/esimidozuj.mccrash

**Comment by Wabbit0101** [comment]
You're using an unstable build of Forge and an unknown build of VanillaFix. The issue seems to be with VanillaFix. If you scroll down in your crash report notice that VFP's exception handler is being triggered by a NullPointerException originating in the VanillaFix mod -- 

> Caused by: java.lang.NullPointerException
    at org.dimdev.vanillafix.blockstates.NumericalBlockState.withProperty(NumericalBlockState.java:130)
    at org.jwaresoftware.mcmods.vfp.common.VfpPantryMultiBlock.<init>(VfpPantryMultiBlock.java:108)

The version of VanillaFix you're using (VanillaFix-1.1.1-134) is unsupported; it does not exist on CurseForge from the list of available downloads (https://minecraft.curseforge.com/projects/vanillafix/files). Try with the most recent supported release for VanillaFix (VanillaFix-1.0.10-99).

**Comment by Rongmario** [comment]
@Wabbit0101 ah my bad, it was a dev version that I forgot to take out :)
