### ISSUE TITLE
[Upsizer] Mushroom stew bug 1.14.4

### ISSUE THREAD

**Issue by MelanX** [Wabbit0101/mods_hoardercraft#86]
https://gfycat.com/specifichomelyasianwaterbuffalo
I think this video says all :)
Mod version: 5.0b2

**Comment by Wabbit0101** [comment]
Yea...that's Mojang's code for ya. As noted in the mod's overview, items that are normally unstackable aren't always guaranteed to work ok if you _consume_ them from a stack. The problem is the code itself assumes a single-stack and blindly sets the item slot to a bowl when player finishes eating. Interestingly, milk buckets, water bottles and potions are coded properly and work just fine. I will change the default configs to no longer upsize stews by default as upsizer cannot "fix" this without patching SoupItem.

(Self) From all 1.14 SoupItem:
```
public ItemStack onItemUseFinish(ItemStack stack, World worldIn, LivingEntity entityLiving) {
      super.onItemUseFinish(stack, worldIn, entityLiving);
      return new ItemStack(Items.BOWL);
   }
```

**Comment by Wabbit0101** [comment]
Defaults changed in next beta.
