### ISSUE TITLE
ArmorUnderwear 1.12.2 - Questions about some config options

### ISSUE THREAD

**Issue by katubug** [Wabbit0101/mods_hoardercraft#90]
Hello! I'm using version 1.0.0 of ArmorUnder, 1.0.0b1 of CarrotsLib, forge 2847. I'm testing the application of liners to various armors for a bug with Pyrotech, but while I was doing this, I found that the "thickness limit" doesn't seem to be working as I'd expected.

When set to 3, it only allows 2 applications of a liner type. When set to 8, it allows 3 applications. When set to 99, it allows 3 applications.

Also, `super_compatibility_mode` states in the description that it's disabled by default, but I am using a freshly generated config, and it's set to `true`.

**Comment by Wabbit0101** [comment]
You are correct about the liner type. That is a known weirdness caused by the default mod recipes. Your override is being overridden by the default mod recipes (which can and do include a limit option). I should probably re-word the config comment. For example for cooling liners for chestplates the recipe itself includes a hard-limit for no more than three liners as represented in the "limit": "COOLEST" line snipped below:
```
{ "_comment": ["Lined chestplate to provide -1 cooling" ],
  "result": {
    "item": "minecraft:leather_chestplate",
    "nbt": {"carrots:ArmorTLining":"COOL"}
  },
  "type": "armorunder:lined_armor_shapeless",
  "limit": "COOLEST",
  "ingredients": [
    { "type": "forge:ore_dict", "ore": "itemChestplate" },
    { "item": "armorunder:cool_chestplate_liner" }
  ]
}
```
For your modpack, if you want to increase the lining limit, you have to use CraftTweaker or similar to remove this recipe and replace it with your own copy -- just DELETE the "limit" line and it should pick up your config value instead. You can repeat this for every armor piece you want to be different from the builtin defaults.

For the supercompatibility config, I cannot recall why I changed the default to true, but the comment was obviously not updated properly. I'll change in the next bugfix version (as MC 1.12.2 is EOL version for TAN, there will be at least one more Armor Underwear bug fix release to address some other requests.)

**Comment by katubug** [comment]
Ah, thank you for the response! That makes more sense now. :) Thanks again!
